project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!archive/"

website:
  title: "RelatE"
  description: "Red Latinoamericana de Ecología/Rede Latino-americana de Ecologia"
  # open-graph:
  #   image: twitter-card-preview_frog-small.png
  #   image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
  # twitter-card:
  #   image: twitter-card-preview_frog-small.png
  #   image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
  #   card-style: summary_large_image
  site-url: https://labs.ala.org.au/
  # favicon: images/favicon.ico
  draft-mode: unlinked
  navbar:
    background: "#222322"
    foreground: "#FFFFFF"
    title: ""
    search: true
    # logo: images/logos/relate_marrom2.jpeg
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - href: about/index.qmd
        text: "Sobre la RelatE"
      - href: posts/index.qmd
        text: "Noticias"
      - text: "Sociedades"
        menu:
        - href: https://abeco.org.br/
          text: "ABECO-Brasil"
        - href: https://scme.mx/
          text: "SCME-México"
        - href: https://www.asaeargentina.com.ar/
          text: "ASAE-Argentina"
        - href: https://www.socecol.cl/
          text: "SOCECOL-Argentina"
      - href: software/index.qmd
        text: "Eventos"
      - href: books/index.qmd
        text: "Blog"
      # - href: gallery/index.qmd
      #   text: "Galeria"
      - href: https://github.com/fplmelo/relate
        icon: github
  announcement:
    icon: info-circle
    dismissable: true
    content: "Estamos inciando nuestras actividades"
    type: light
    position: below-navbar

format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [theme.css, custom_theme.scss]
    toc: true
    code-overflow: scroll
    linkcolor: "#B8573E"
    # include-before-body: _fathom.html

freeze: true



