---
title: "Sobre nosotros"
lang: es
subtitle: Las personas abajo somos las que estamos trabajando para consolidar la RelatE inicialmente
format: html 
title-block-banner: "#E06E53"
title-block-banner-color: body
---

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#| include: false
library(htmltools)
source("../R/functions.R")
```

Somos las personas que se reunieron incialmente pra fundar la **RelatE** y luego que tengamos la red consolidada, habrá mecanismos democráticos de elección de la primera junta directiva.

### Nuestras tareas son:  

- Comunicación entre Sociedades de Ecología
- Divulgación de eventos
- Creación y consolidación de estatutos




# Quienes somos

*Haga click en las fotos*
```{r}
#| echo: false
tags$div(class = "row",# Create a row for 3 team-member cards
         
create_team_card(
  person_page = "maria_noel/index.html",
  img_src = "../images/people/maria.png",
  name = "María Noel Clerici Hirschfeld",
  text = "Uruguay"
),
create_team_card(
  person_page = "lucas/index.html",
  img_src = "../images/people/lucas.jpg",
  name = "Lucas Enrico",
  text = "Argentina"
),
create_team_card(
  person_page = "felipe/index.html",
  img_src = "../images/people/felipe.jpg",
  name = "Felipe Melo",
  text = "Brasil"
)
)
tags$div(class = "row", # Create a row for 3 team-member cards
         
create_team_card(
  person_page = "laura/index.html",
  img_src = "../images/people/laura.png",
  name = "Laura Yahdjian",
  text = "Argentina"
),
create_team_card(
  person_page = "alejandro/index.html",
  img_src = "../images/people/alejandro.png",
  name = "Alejandro Baseiro",
  text = "Uruguay"
),
create_team_card(
  person_page = "nico/index.html",
  img_src = "../images/people/nico.png",
  name = "Nicolás Urbina",
  text = "Colombia"
),
)
tags$div(class = "row", # Create a row for 3 team-member cards

create_team_card(
  person_page = "wesley/index.html",
  img_src = "../images/people/wesley.png",
  name = "Wesley Dáttilo",
  text = "México"
),
create_team_card(
  person_page = "jorge/index.html",
  img_src = "../images/people/jorge.png",
  name = "Jorge Dayvis",
  text = "Cuba"
),
create_team_card(
  person_page = "leonel/index.html",
  img_src = "../images/people/leonel.png",
  name = "Leonel Sierralta",
  text = "Chile"
)
)  

```

